mysql:
  image: mysql
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=Sup1nf0

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - 8080:80

websocket:
  image: offlinegmbh/socketio
  links:
  - mysql:db
  volumes:
  - ./source-sp/server/server.js:/srv/socket.js
  - ./.data/websocket:/srv/logs
  ports:
  - "3000:3000"