redis:
  image: redis:alpine

websocket:
  image: offlinegmbh/socketio
  links:
  - redis
  volumes:
  - ./source-sp/server/server.js:/srv/socket.js
  - ./.data/websocket:/srv/logs
  ports:
  - "4242:3000"